version: "3.2"

networks:
   frontend:
   backend:

services:
    webmvc:
        build:
            context: src\WebMvc\WebMvc
            dockerfile: DockerFile
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development 
            - CatalogUrl=http://catalog
        container_name: webshop
        ports:
            - "5500:80"
        networks:
            - frontend 
        depends_on:
            - catalog

    catalog:
        build:
            context: src\Services\ProductCatelogApi
            dockerfile: DockerFile
        image: shoes/catalog
        environment:
            - DatabaseServer=mssqlserver
            - DatabaseName=CatalogDb
            - DatabaseUser=sa
            - DatabasePassword=Ringer#123
        container_name: catalogapi
        ports:
            - "5000:80"
        networks:
            - backend
            - frontend
        depends_on:
            - mssqlserver
         
    mssqlserver:
        image: "microsoft/mssql-server-linux:latest"
        ports:
            - "1401:1433"

        container_name: mssqlcontainer
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Ringer#123
        networks:
            - backend